version: '3.8'

services:
  youtube-video-download-worker-0:
    image: "panda1024/pku-ece-cv:v2.1"
    deploy:
      replicas: 12
    environment:
      - CLOUD_CONFIG=external
      - GFW=false
    restart: always
    command:
      [
          "bash",
          "-c",
          "conda run --no-capture-output --name pku-ece-cv rq worker pku_single_video_spider2 --url redis://:cGt1X3JlZGlz@42.193.252.170:6379 --path ./ --name COCO-1_worker-$$RANDOM"
      ]
